### ISSUE TITLE
Facing issue in iOS 12.4

### ISSUE THREAD

**Issue by rahuleastern** [PauliusVindzigelskis/NGSPopoverView#2]
It's working fine in iOS 13 but facing issue in iOS 12.4 
![Screenshot 2019-10-30 at 2 30 44 PM](https://user-images.githubusercontent.com/57174222/67844836-73b2c180-fb24-11e9-8c18-504de570fa7f.png)

**Comment by PauliusVindzigelskis** [comment]
I'll take a look at that once I get few minutes free. In the meantime, if you find a way to fix it, you can always make a pull request

**Comment by PauliusVindzigelskis** [comment]
I'm unable to reproduce in demo app. What container are You using to represent this label?

**Comment by rahuleastern** [comment]
Hi, thank you for response. I solved this issue and issue is from my side. Thank you.

**Comment by PauliusVindzigelskis** [comment]
No problem
